version: "3.9"

services:

  # =========================
  # Customer MySQL
  # =========================
  customer-mysql:
    image: mysql:8.4
    container_name: quantumcart-customer-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "${DB_PORT}:3306"

    volumes:
      - customer_mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u${DB_ROOT_USER}",
          "-p${DB_ROOT_PASSWORD}"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

    restart: unless-stopped

  # =========================
  # Customer Service
  # =========================
  customer-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: quantumcart-customer-service

    environment:
      NODE_ENV: development

      PORT: 8007

      DB_HOST: customer-mysql
      DB_PORT: 3306

      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      DB_CONNECTION_LIMIT: ${DB_CONNECTION_LIMIT}

      DB_ROOT_USER: ${DB_ROOT_USER}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

    ports:
      - "8007:8007"

    depends_on:
      customer-mysql:
        condition: service_healthy

    restart: unless-stopped

    # =========================
  # Customer Database Migration
  # =========================
  
    # =========================
  # Customer Database Migration
  # =========================
  customer-migration:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: quantumcart-customer-migration

    environment:
      NODE_ENV: development

      DB_HOST: customer-mysql
      DB_PORT: 3306

      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      DB_CONNECTION_LIMIT: ${DB_CONNECTION_LIMIT}

      DB_ROOT_USER: ${DB_ROOT_USER}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

    depends_on:
      customer-mysql:
        condition: service_healthy

    command:
      [
        "node",
        "dist/scripts/migrate.js"
      ]

volumes:
  customer_mysql_data: